language: python

cache: pip

addons:
  apt:
    packages:
    - chromium-browser
    - chromium-chromedriver

branches:
  only:
    - master

jobs:
  include:
    - name: "Python on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
    - name: "Python on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

# command to install dependencies
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install --user -r requirements.txt

# command to run tests
script: python3 -m unittest test || python -m unittest test 
