language: python

cache: pip

dist: xenial

addons:
  apt:
    packages:
    - firefox
    - chromium-browser
    - chromium-chromedriver

branches:
  only:
    - master

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - python -m unittest test
