# GitHub Actions Workflow for navchandar/Naukri repo
# File location: .github/workflows/naukri-daily-update.yml

name: Naukri Daily Auto Update

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 8:30 AM IST
  workflow_dispatch:

jobs:
  update-naukri-profile:
    runs-on: ubuntu-latesdt
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Naukri updater
        env:
          USERNAME: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MOBILE: ${{ secrets.MOBILE }}
        run: |
          echo "ORIGINAL_RESUME_PATH = 'Aadish_SDE2_Backend_2025.pdf'" > constants.py
          echo "MODIFIED_RESUME_PATH = 'Aadish_SDE2_Backend_2025.pdf'" >> constants.py
          echo "USERNAME = '${{ secrets.EMAIL }}'" >> constants.py
          echo "PASSWORD = '${{ secrets.PASSWORD }}'" >> constants.py
          echo "MOBILE = '${{ secrets.MOBILE }}'" >> constants.py
          echo "NAUKRI_LOGIN_URL = 'https://www.naukri.com/nlogin/login'" >> constants.py
          echo "NAUKRI_PROFILE_URL = 'https://www.naukri.com/mnjuser/profile'" >> constants.py
          python naukri.py
