name: Naukri Daily Auto Update

on:
  schedule:
    - cron: '0 3 * * *'  # 8:30 AM IST
  workflow_dispatch:

jobs:
  update-naukri-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome v138 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 libatk-bridge2.0-0 libgtk-3-0 libgbm-dev
          
          wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.168/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome
          sudo ln -sf /opt/chrome/chrome /usr/bin/google-chrome

          wget https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.168/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create constants.py from secrets
        run: |
          echo "USERNAME = '${{ secrets.EMAIL }}'" > constants.py
          echo "PASSWORD = '${{ secrets.PASSWORD }}'" >> constants.py
          echo "MOBILE = '${{ secrets.MOBILE }}'" >> constants.py
          echo "ORIGINAL_RESUME_PATH = 'Aadish_SDE2_Backend_2025.pdf'" >> constants.py
          echo "MODIFIED_RESUME_PATH = 'Aadish_SDE2_Backend_2025.pdf'" >> constants.py
          echo "NAUKRI_LOGIN_URL = 'https://www.naukri.com/nlogin/login'" >> constants.py
          echo "NAUKRI_PROFILE_URL = 'https://www.naukri.com/mnjuser/profile'" >> constants.py

      - name: Run script
        run: xvfb-run python naukri.py
