name: Naukri Daily Auto Update

on:
  schedule:
    - cron: '0 3 * * *'  # 8:30 AM IST
  workflow_dispatch:

jobs:
  update-naukri-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libnss3 libxss1 libatk-bridge2.0-0 libgtk-3-0 libgbm-dev
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          wget -N https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create constants.py from secrets
        run: |
          echo "USERNAME = '${{ secrets.EMAIL }}'" > constants.py
          echo "PASSWORD = '${{ secrets.PASSWORD }}'" >> constants.py
          echo "MOBILE = '${{ secrets.MOBILE }}'" >> constants.py

      - name: Run script
        run: xvfb-run python naukri.py
